config/routes.rb
TwitterClone::Application.routes.draw do
  root :to => "users#index"
  resources :tweets

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users do
    member do
      get :toggle_follow
    end
  end

end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :user
  belongs_to :follower, :class_name => "User", :foreign_key => "follower_id"
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  cattr_reader :per_page
  @@per_page = 10

  default_scope order("created_at DESC")

  validates :user, :presence => true
  validates :text, :length => 1..140 
end

app/models/user.rb
class User < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :username, :email, :password, :password_confirmation

  attr_accessor :password
  before_save :prepare_password

  validates_presence_of :username
  validates_uniqueness_of :username, :email, :allow_blank => true
  validates_format_of :username, :with => /^[-\w\._@]+$/i, :allow_blank => true, :message => "should only contain letters, numbers, or .-_@"
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true

  has_many :tweets
  has_many :followers, :class_name => "Follow", :foreign_key => "user_id"
  has_many :following, :class_name => "Follow", :foreign_key => "follower_id"

  # login can be either username or email address
  def self.authenticate(login, pass)
    user = find_by_username(login) || find_by_email(login)
    return user if user && user.matching_password?(pass)
  end

  def matching_password?(pass)
    self.password_hash == encrypt_password(pass)
  end

  private

  def prepare_password
    unless password.blank?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = encrypt_password(password)
    end
  end

  def encrypt_password(pass)
    BCrypt::Engine.hash_secret(pass, password_salt)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ControllerAuthentication
  protect_from_forgery
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:login], params[:password])
    if user
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully."
      redirect_to_target_or_default("/")
    else
      flash.now[:error] = "Invalid login or password."
      render :action => 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out."
    redirect_to "/"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_filter :login_required

  def create
    @tweet = Tweet.new(params[:tweet])
    @tweet.user = current_user
    if @tweet.save
      flash[:notice] = "Successfully created tweet."
    else
      flash[:error] = "OOPS! Something went wrong!"
    end
    redirect_to :root
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    flash[:notice] = "Successfully destroyed tweet."
    redirect_to tweets_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required, :except => [:new, :create]
  
  def index
    @tweets = Tweet.where(:user_id => [current_user.id] + current_user.following.collect(&:user_id)).paginate(:page => params[:page]) 
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thank you for signing up! You are now logged in."
      redirect_to "/"
    else
      render :action => 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      flash[:notice] = "Your profile has been updated."
      redirect_to "/"
    else
      render :action => 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets.paginate(:page => params[:page])
  end

  def toggle_follow
    where = {:user_id => params[:id], :follower_id => current_user.id}
    if follow = Follow.where(where).first
      follow.destroy
    else
      follow = Follow.create!(where)
    end
    redirect_to follow.user 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag "application"
    = javascript_include_tag :all
    = csrf_meta_tag
    = yield(:head)

  %body
    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"

      - if show_title?
        %h1= yield(:title)

      = yield

app/views/tweets/_form.html.haml
= form_for @tweet do |f|
  = f.error_messages
  %p
    = f.label :user_id
    %br
    = f.text_field :user_id
  %p
    = f.label :text
    %br
    = f.text_field :text
  %p
    = f.submit

app/views/tweets/edit.html.haml
- title "Edit Tweet"

= render 'form'

%p
  = link_to "Show", tweet
  |
  = link_to "View All", tweets_path

app/views/tweets/index.html.haml
- title "Tweets"

%table
  %tr
    %th User
    %th Text
  - for tweet in @tweets
    %tr
      %td= tweet.user_id
      %td= tweet.text
      %td= link_to 'Show', tweet
      %td= link_to 'Edit', edit_tweet_path(tweet)
      %td= link_to 'Destroy', tweet, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Tweet", new_tweet_path(tweet)

app/views/tweets/new.html.haml
- title "New Tweet"

= render 'form'

%p= link_to "Back to List", tweets_path

app/views/tweets/show.html.haml
- title "Tweet"

%p
  %strong User:
  = @tweet.user_id
%p
  %strong Text:
  = @tweet.text

%p
  = link_to "Edit", edit_tweet_path(@tweet)
  |
  = link_to "Destroy", @tweet, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", tweets_path

app/views/users/_form.html.haml
= form_for @user do |f|
  = f.error_messages
  %p
    = f.label :username
    %br
    = f.text_field :username
  %p
    = f.label :email, "Email Address"
    %br
    = f.text_field :email
  %p
    = f.label :password
    %br
    = f.password_field :password
  %p
    = f.label :password_confirmation, "Confirm Password"
    %br
    = f.password_field :password_confirmation
  %p
    = f.submit (@user.new_record? ? "Sign up" : "Update")

app/views/users/edit.html.haml
- title "Sign up"

= render 'form'

app/views/users/index.html.haml
= form_for Tweet.new do |f|
  = f.text_area :text
  = f.submit

%ol
  - @tweets.each do |tweet|
    %li= tweet.text

= will_paginate @tweets 

app/views/users/new.html.haml
- title "Sign up"

%p== Already have an account? #{link_to "Log in", login_path}.

= render 'form'

app/views/users/show.html.haml
%dl
  %dt
    Username
  %dd
    = @user.username
  %dt
    Email
  %dd
    = @user.email
  %dt

  %dd
    = link_to toggle_follow_user_path(@user) do
      = Follow.exists?(:user_id => @user.id, :follower_id => current_user.id) ? "Unfollow" : "Follow"

%ul
  - @tweets.each do |tweet|
    %li
      = tweet.text